version: "3"
services:
  monolith:
    image: php:7
    command: ["php", "-S", "0.0.0.0:8081", "/app/index.php"]
    ports:
      - 8081:8081
    volumes:
      - ../01-monolith/:/app
  krakend:
    image: devopsfaith/krakend
    volumes:
      - ./:/etc/krakend
    ports:
      - 8080:8080